### ISSUE TITLE
One or more keys necessary for output format <0> are missing.

### ISSUE THREAD

**Issue by jose-martinez-fignoni** [BioComputingUP/MobiDB-lite#2]
Hi guys! I am getting a missing keys error for some predictors. Below is the command and error message. I have changed nothing in the `config.ini` file, which was working before. Any ideas how to fix it? tks!

```
Command: python3 bin/mobidb/2.0/mobidb_lite.py /mnt/efs/genomes/results/SYM57343/WGS18118/ASM-txvdzN/annotation/ANN-79MFN4JTs/iprscan_822/temp/ip-172-60-37-232.ec2.internal_20221007_025458642_kvow//jobMobiDBLite/000000000001_000000000492.fasta

Error output from binary:

| ERROR    | One or more keys necessary for output format <0> are missing. Check your config.ini and make sure that all necessary keys are present. | MISSING KEY(S): ._disembl; ._espritz; ._iupred; ._globplot
```

The content from my `config.ini` file:
```[bin_directories]
# absolute path to the predictor folder
# ! DONT DELETE UNASSIGNED KEYS !
anchor=
disembl=
dynamine=
espritz=
fess=
globplot=
iupred=
jronn=
pfilt=
seg=
vsl2=

[thresholds]
mdb=0.625
anchor=0.5
dis465=0.5
disHL=0.086
dynamine_coil=0.5
espD=0.5072
espN=0.3089
espX=0.1434
iupl=0.5
iups=0.5
glo=0.0
jronn=0.5
pfilt=0.5
seg=0.5
vsl=0.5
fess_helix=0.5
fess_sheet=0.5
fess_coil=0.5

[outfmt_groups]
0=main
1=main
2=mobidb3
3=allid
```

**Comment by damianopiovesan** [comment]
Hi Jose. Can you share the input sequence? Do you have Python2 installed? Have you tried running mobidb_lite.py from its folder?

**Comment by jose-martinez-fignoni** [comment]
Hi Damiano! Tks for your quick reply. I am running this through the InterproScan, in Python3. It was working fine until I upgraded the InterproScan version because of a different issue.

I don't think I can get the input sequence easily, I am not using the software myself but just trying to fix it for a different team.

Sorry for being so little helpful, any idea what this can be related to? Will try getting an input sequence in case it's needed for solving this.

tks!
________________________________

**Comment by matthiasblum** [comment]
Hi @jose-martinez-fignoni ,

We replied to your issue in ebi-pf-team/interproscan#294. Briefly, MobiDB-lite cannot find the path to predictor executables if `[bin_directories]` is missing in the `config.ini` file.
