### ISSUE TITLE
Need help with predictors not provided

### ISSUE THREAD

**Issue by seoanezonjic** [BioComputingUP/MobiDB-lite#3]
Hi MobiDB-lite
Could you provide information about where  download and how to configure the predictors that are not packaged with the code? i find very difficult to find the software and download the needed files.
Also I ask you about the B2BTools (https://pypi.org/project/b2bTools) python package. It includes several predictors (some that you use). Could yo give support to this package to provide additional predictors?
Thank you in advance
Pedro Seoane

**Comment by damianopiovesan** [comment]
## Disorder calculation

### Executables included in the repo 
* DisEMBL http://dis.embl.de/DisEMBL-1.4.tgz
* ESpritz (requires permission) https://biocomputingup.it/downloads
* GlobPlot http://globplot.embl.de/html/GlobPipe-2.3.tgz and https://www.mpipks-dresden.mpg.de/tisean//archive.html#source
* IUPred (version 1 is not available for download anymore)
* SEG https://ftp.ncbi.nih.gov/pub/seg/seg/

### Not included
* Jronn (available inside BioJava, unsupported) https://github.com/biojava/biojava

## Additional methods (not used for the calculation of disorder consensus)
* FeSS (requires permission) https://biocomputingup.it/downloads
* ANCHOR (requires permission) http://anchor.elte.hu/Downloads.php
* Pfilt http://bioinfadmin.cs.ucl.ac.uk/downloads/pfilt/
* Dynamine (version 1 is not available for download anymore)
